version: "3.4"
services:
  web:
    image: bernard0926/flaskprojecttcmg412
    environment:
      - SLACK_URL
    ports:
      - "80:5000"
    networks:
      - webnet
  redis-server: 
    image: redis
    networks:
      - webnet
networks:
  webnet:

